### ISSUE TITLE
导入的50万条数据放哪里了？--不好意思，问题弱爆了，初学

### ISSUE THREAD

**Issue by jouniana** [eBay/accelerator-project_skeleton#1]
导入的50万条数据放哪里了？是我本地安装该工具的，是导入到我的计算机本地了吗？

不好意思，问题弱爆了，初学

**Comment by berkeman** [comment]
I assume the question is where the data generated by the example is stored.

All data produced by the Accelerator is stored in a "workdir", defined in the configuration file "conf/framework.conf".  In the default setup this corresponds to "${HOME}/accelerator/workdirs/TEST/".  All jobs in the example will be stored there.  For example, if a "csvexport" job has jobid "TEST-5", you'll find the created file in "${HOME}/accelerator/workdirs/TEST/TEST-5/".

Actually, the bundled example code will print the location of the output files to standard out.  If you look at page 3 of the installation document, you'll find this:  "Exported file stored in "/home/ab/accelerator/workdirs/TEST/TEST-5/random.tsv".

All data used in this example is created using Python's random module.  There is no import of external data.
